name: 'Get Next Version'
description: 'Get the next version for a project release based on conventional commits'
author: UGRC
branding:
  icon: 'arrow-right-circle'
  color: 'purple'
inputs:
  prerelease:
    description: 'Determines if the proposed version number includes a prerelease tag (e.g. 1.0.0-rc.1)'
    required: false
    default: 'false'
  repo-token:
    description: 'A token with access to your repo (e.g. {{ secrets.GITHUB_TOKEN }})'
    required: true
outputs:
  version:
    description: 'The new version e.g. (v1.0.0)'
  major:
    description: 'The new major version number e.g. (1)'
  minor:
    description: 'The new minor version number e.g. (0)'
  patch:
    description: 'The new patch version number e.g. (0)'
  current-version-number:
    description: 'The current version number e.g. (1.0.0)'
runs:
  using: 'node20'
  main: 'dist/index.js'
