onlyBuiltDependencies:
  - esbuild

overrides:
  '@eslint/plugin-kit@<0.3.4': '>=0.3.4'
  esbuild@<=0.24.2: '>=0.25.0'
  js-yaml@>=4.0.0 <4.1.1: '>=4.1.1'
  storybook@>=9.0.0 <9.1.17: '>=9.1.17'
  undici@<6.23.0: '>=6.23.0'
  vite@<5.4.21: '>=5.4.21'
